version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: newsletter-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsletter
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsletter-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      POSTGRES_PRISMA_URL: postgresql://postgres:postgres@postgres:5432/newsletter
      POSTGRES_URL_NON_POOLING: postgresql://postgres:postgres@postgres:5432/newsletter
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres-data:
